extends Node
## "Sfx" autoload — sound playback for the whole game.
##
## All audio is procedurally generated by tools/asset_gen/generate_audio.gd.
##   Sfx.play("swing")                  — 2D/UI sound
##   Sfx.play3d("hit", pos)             — positional sound
## Music and wind ambience start automatically. Loop flags for music/wind/hum
## are set here at runtime (shared resources), so scene files stay simple.

const PATHS := {
	"swing": "res://assets/audio/swing.wav",
	"hit": "res://assets/audio/hit.wav",
	"bite": "res://assets/audio/bite.wav",
	"growl": "res://assets/audio/growl.wav",
	"raptor_hurt": "res://assets/audio/raptor_hurt.wav",
	"raptor_die": "res://assets/audio/raptor_die.wav",
	"player_hurt": "res://assets/audio/player_hurt.wav",
	"jump": "res://assets/audio/jump.wav",
	"step": "res://assets/audio/step.wav",
	"absorb": "res://assets/audio/absorb.wav",
	"block": "res://assets/audio/block.wav",
	"dash": "res://assets/audio/dash.wav",
	"chomp": "res://assets/audio/chomp.wav",
	"sweep": "res://assets/audio/sweep.wav",
	"heavy": "res://assets/audio/heavy.wav",
	"land": "res://assets/audio/land.wav",
	"heartbeat": "res://assets/audio/heartbeat.wav",
	"bird1": "res://assets/audio/bird1.wav",
	"bird2": "res://assets/audio/bird2.wav",
	"chitter": "res://assets/audio/chitter.wav",
	"distant_roar": "res://assets/audio/distant_roar.wav",
	"wind": "res://assets/audio/wind.wav",
	"hum": "res://assets/audio/hum.wav",
	"music": "res://assets/audio/music.wav",
}
const LOOPED := ["wind", "hum", "music"]

var _streams := {}
var _pool_3d: Array[AudioStreamPlayer3D] = []
var _pool_2d: Array[AudioStreamPlayer] = []
var _idx_3d := 0
var _idx_2d := 0


func _ready() -> void:
	for key in PATHS:
		if ResourceLoader.exists(PATHS[key]):
			_streams[key] = load(PATHS[key])
		else:
			push_warning("Sfx: missing %s — run tools/asset_gen/generate_audio.gd" % PATHS[key])

	# Mark loops on the shared resources so every player of these streams loops.
	for key in LOOPED:
		var s: AudioStreamWAV = _streams.get(key)
		if s:
			s.loop_mode = AudioStreamWAV.LOOP_FORWARD
			s.loop_end = s.data.size() / 2  # frames (16-bit mono = 2 bytes/frame)

	for i in 14:
		var p := AudioStreamPlayer3D.new()
		p.unit_size = 6.0
		p.max_db = 3.0
		add_child(p)
		_pool_3d.append(p)
	for i in 6:
		var p := AudioStreamPlayer.new()
		add_child(p)
		_pool_2d.append(p)

	_start_loop("music", -9.0)
	_start_loop("wind", -17.0)


func play(sfx_name: String, volume_db := 0.0, pitch := 1.0, pitch_var := 0.05) -> void:
	if not _streams.has(sfx_name):
		return
	var p := _pool_2d[_idx_2d]
	_idx_2d = (_idx_2d + 1) % _pool_2d.size()
	p.stream = _streams[sfx_name]
	p.volume_db = volume_db
	p.pitch_scale = pitch * (1.0 + randf_range(-pitch_var, pitch_var))
	p.play()


func play3d(sfx_name: String, pos: Vector3, volume_db := 0.0, pitch := 1.0,
		pitch_var := 0.08) -> void:
	if not _streams.has(sfx_name):
		return
	var p := _pool_3d[_idx_3d]
	_idx_3d = (_idx_3d + 1) % _pool_3d.size()
	p.global_position = pos
	p.stream = _streams[sfx_name]
	p.volume_db = volume_db
	p.pitch_scale = pitch * (1.0 + randf_range(-pitch_var, pitch_var))
	p.play()


func _start_loop(sfx_name: String, volume_db: float) -> void:
	if not _streams.has(sfx_name):
		return
	var p := AudioStreamPlayer.new()
	p.stream = _streams[sfx_name]
	p.volume_db = volume_db
	add_child(p)
	p.play()
